(()=>{"use strict";
const DB="sps-lager-db",STORE="articles";let db,scanner=null,current=null;
const $=id=>document.getElementById(id),views=[...document.querySelectorAll(".view")];
function show(id){views.forEach(v=>v.classList.toggle("active",v.id===id));scrollTo(0,0)}
function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2200)}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"barcode"})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function os(m="readonly"){return db.transaction(STORE,m).objectStore(STORE)}
function get(code){return new Promise((ok,no)=>{const r=os().get(code);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>no(r.error)})}
function all(){return new Promise((ok,no)=>{const r=os().getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>no(r.error)})}
function put(a){return new Promise((ok,no)=>{const r=os("readwrite").put(a);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}
async function summary(){const a=await all(),n=a.reduce((s,x)=>s+Number(x.stock||0),0);$("articleCount").textContent=`${a.length} Artikel`;$("pieceCount").textContent=`${n} Stück total`}
async function stop(){if(!scanner)return;try{if(scanner.isScanning)await scanner.stop();await scanner.clear()}catch(e){}scanner=null}
async function handle(raw){const code=String(raw||"").trim();if(!code)return;await stop();const a=await get(code);a?openAdjust(a):openNew(code)}
function openNew(code=""){current=null;$("editMode").textContent="NEUER ARTIKEL";$("editTitle").textContent="SPS-Karte anlegen";$("barcode").disabled=false;$("barcode").value=code;$("name").value="";$("stock").value=0;$("stockWrap").style.display="block";show("edit");setTimeout(()=>$("name").focus(),100)}
function openEdit(a){current=a;$("editMode").textContent="ARTIKEL BEARBEITEN";$("editTitle").textContent=a.name;$("barcode").disabled=true;$("barcode").value=a.barcode;$("name").value=a.name;$("stockWrap").style.display="none";show("edit")}
function openAdjust(a){current=a;$("adjustName").textContent=a.name;$("currentStock").textContent=a.stock;$("delta").value=-1;show("adjust")}
async function startScan(){show("scanner");$("scanStatus").textContent="Kamera wird vorbereitet …";if(!window.Html5Qrcode){$("scanStatus").textContent="Scannerbibliothek konnte nicht geladen werden.";return}try{scanner=new Html5Qrcode("reader");await scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:280,height:160},aspectRatio:1.777778},x=>handle(x),()=>{});$("scanStatus").textContent="Barcode ruhig in den Rahmen halten."}catch(e){console.error(e);$("scanStatus").textContent="Kamera konnte nicht gestartet werden. Berechtigung prüfen."}}
async function render(q=""){const a=(await all()).filter(x=>!q||x.name.toLowerCase().includes(q.toLowerCase())||x.barcode.toLowerCase().includes(q.toLowerCase())).sort((x,y)=>x.name.localeCompare(y.name,"de"));const box=$("items");box.innerHTML="";if(!a.length){box.innerHTML='<div class="empty">Noch keine passenden Artikel vorhanden.</div>';return}a.forEach(x=>{const d=document.createElement("div");d.className="item";d.innerHTML='<button><div class="iname"></div><div class="icode"></div></button><div class="qty"></div>';d.querySelector(".iname").textContent=x.name;d.querySelector(".icode").textContent=x.barcode;d.querySelector(".qty").textContent=x.stock;d.querySelector("button").onclick=()=>openAdjust(x);box.appendChild(d)})}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function csv(v){return `"${String(v??"").replaceAll('"','""')}"`}
function stamp(){return new Date().toISOString().slice(0,10)}
async function share(blob,name){const f=new File([blob],name,{type:blob.type});if(navigator.canShare&&navigator.canShare({files:[f]})){await navigator.share({files:[f],title:name});return}const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function exportCsv(){const a=(await all()).sort((x,y)=>x.name.localeCompare(y.name,"de"));const r=[["Barcode","Artikelname","Bestand","Letzte Änderung"],...a.map(x=>[x.barcode,x.name,x.stock,x.updatedAt||""])];await share(new Blob(["\ufeff"+r.map(z=>z.map(csv).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8"}),`SPS-Lager_${stamp()}.csv`)}
async function exportXls(){const a=(await all()).sort((x,y)=>x.name.localeCompare(y.name,"de"));const rows=a.map(x=>`<tr><td>${esc(x.barcode)}</td><td>${esc(x.name)}</td><td>${x.stock}</td><td>${esc(x.updatedAt||"")}</td></tr>`).join("");await share(new Blob([`<html><meta charset="utf-8"><table><tr><th>Barcode</th><th>Artikelname</th><th>Bestand</th><th>Letzte Änderung</th></tr>${rows}</table></html>`],{type:"application/vnd.ms-excel"}),`SPS-Lager_${stamp()}.xls`)}
async function backup(){const p={app:"SPS Lager",version:"0.3",exportedAt:new Date().toISOString(),articles:await all()};await share(new Blob([JSON.stringify(p,null,2)],{type:"application/json"}),`SPS-Lager_Backup_${stamp()}.json`)}
async function pdf(){const a=(await all()).sort((x,y)=>x.name.localeCompare(y.name,"de")),rows=a.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.barcode)}</td><td>${x.stock}</td></tr>`).join(""),w=open("","_blank");if(!w){toast("Pop-ups für PDF bitte erlauben.");return}w.document.write(`<html><meta charset="utf-8"><style>body{font-family:sans-serif;padding:24px}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #ddd;padding:9px;text-align:left}</style><h1>SPS Lagerübersicht</h1><p>${new Date().toLocaleString("de-CH")}</p><table><tr><th>Artikel</th><th>Barcode</th><th>Bestand</th></tr>${rows}</table><script>onload=()=>setTimeout(()=>print(),300)<\/script></html>`);w.document.close()}
document.addEventListener("DOMContentLoaded",async()=>{db=await openDb();await summary();
$("scanBtn").onclick=startScan;$("manualBtn").onclick=()=>{const c=prompt("Barcode oder Artikelcode eingeben:");if(c)handle(c)};$("listBtn").onclick=async()=>{await render();show("inventory")};$("exportBtn").onclick=()=>show("exports");$("stopScan").onclick=async()=>{await stop();show("home")};
document.querySelectorAll(".back").forEach(b=>b.onclick=async()=>{await stop();show("home");summary()});
$("articleForm").onsubmit=async e=>{e.preventDefault();const a={barcode:$("barcode").value.trim(),name:$("name").value.trim(),stock:current?current.stock:Math.max(0,Number($("stock").value||0)),updatedAt:new Date().toISOString()};await put(a);await summary();toast("Artikel gespeichert.");openAdjust(a)};
document.querySelectorAll("[data-delta]").forEach(b=>b.onclick=()=>$("delta").value=b.dataset.delta);
$("bookBtn").onclick=async()=>{const d=Number($("delta").value||0);if(!Number.isInteger(d)||d===0){toast("Ganze Zahl ungleich 0 eingeben.");return}if(current.stock+d<0){toast("Bestand kann nicht unter 0 fallen.");return}current={...current,stock:current.stock+d,updatedAt:new Date().toISOString()};await put(current);$("currentStock").textContent=current.stock;await summary();toast(`${d>0?"+":""}${d} Stück gebucht.`)};
$("editBtn").onclick=()=>openEdit(current);$("search").oninput=e=>render(e.target.value);$("csvBtn").onclick=()=>exportCsv().catch(e=>toast(e.message));$("xlsBtn").onclick=()=>exportXls().catch(e=>toast(e.message));$("pdfBtn").onclick=pdf;$("backupBtn").onclick=backup;$("restore").onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());for(const a of p.articles||[])await put(a);await summary();toast("Backup wiederhergestellt.")}catch(x){toast("Backup konnte nicht gelesen werden.")}e.target.value=""};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js").catch(console.warn)});
})();